controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
  - name: fake_left_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_fts_tool
  - name: fake_right_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_fts_tool
  - name: fake_dual_arms_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: ready_pose
  - group: right_arm
    pose: ready_pose
  - group: dual_arms
    pose: right_push