arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_joint_1
    - left_arm_joint_2
    - left_arm_joint_3
    - left_arm_joint_4
    - left_arm_joint_5
    - left_arm_joint_6
    - left_arm_fts_tool
    - right_arm_joint_1
    - right_arm_joint_2
    - right_arm_joint_3
    - right_arm_joint_4
    - right_arm_joint_5
    - right_arm_joint_6
    - right_arm_fts_tool
  gains:
    left_arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_fts_tool:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_fts_tool:
      p: 100
      d: 1
      i: 1
      i_clamp: 1